name: build ffmpeg (macOS)

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # 支持手动触发

jobs:
  build-macos:
    name: build in native macOS
    runs-on: macos-15
    steps:
      - name: Checkout ffmpeg-build-script
        uses: actions/checkout@v4
        with:
          repository: markus-perl/ffmpeg-build-script
          ref: master   # 可以换成 tag，例如 "20240710"

      - name: build ffmpeg
        run: |
          while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
          SKIPINSTALL=yes VERBOSE=yes ./build-ffmpeg --build --enable-gpl-and-non-free --latest --full-static 
          kill %1

      - name: check shared library
        run: |
          otool -L ./workspace/bin/ffmpeg

      - name: test run ffmpeg
        run: |
          ./workspace/bin/ffmpeg -buildconf

      - name: Upload ffmpeg binaries
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-macos-bin
          path: |
            ./workspace/bin/ffmpeg
            ./workspace/bin/ffprobe

      - name: clean up
        run: |
          ./build-ffmpeg --cleanup
