name: FF FFmpeg Static Build (macOS Apple Silicon)

# 触发条件：手动触发 + 推送到main分支时触发
on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14  # 使用最新macOS runner（支持Apple Silicon）
    steps:
      - name: 检查源码
        uses: actions/checkout@v4

      - name: 安装Homebrew并更新
        run: |
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          brew tap homebrew-ffmpeg/ffmpeg
          brew update && brew upgrade
          brew install homebrew-ffmpeg/ffmpeg/ffmpeg --HEAD

      - name: 测试
        run: |
          ffmpeg -v

