name: Build Native FFmpeg for Apple Silicon

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-native:
    runs-on: macos-14
    timeout-minutes: 180

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update > /dev/null 2>&1
        brew install --quiet pkg-config nasm yasm cmake autoconf automake libtool
        brew install --quiet x264 x265 lame opus libvorbis libvpx webp fdk-aac freetype fontconfig
        brew link --overwrite nasm yasm autoconf automake libtool x264 x265 lame opus libvorbis libvpx webp fdk-aac > /dev/null 2>&1 || true
        HOMEBREW_PREFIX=$(brew --prefix)
        export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"

    - name: Download FFmpeg source
      run: |
        if [ ! -d "ffmpeg-src" ]; then
          curl -L "https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2" -o ffmpeg.tar.bz2
          tar -xjf ffmpeg.tar.bz2
          mv ffmpeg ffmpeg-src
          rm ffmpeg.tar.bz2
        fi

    - name: Configure FFmpeg for Apple Silicon (static, no X11)
      working-directory: ffmpeg-src
      run: |
        ./configure \
          --prefix=/usr/local \
          --target-os=darwin \
          --arch=arm64 \
          --disable-shared \
          --enable-static \
          --disable-ffplay \
          --disable-x11 \
          --disable-opengl \
          --disable-doc \
          --disable-debug \
          --enable-gpl \
          --enable-nonfree \
          --enable-videotoolbox \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libvpx \
          --enable-libfdk-aac \
          --enable-libopus \
          --enable-libvorbis \
          --enable-libwebp \
          --enable-libmp3lame \
          --enable-avfilter

    - name: Build FFmpeg
      working-directory: ffmpeg-src
      run: make -j$(sysctl -n hw.ncpu)

    - name: Package binaries
      run: |
        mkdir -p release
        cp ffmpeg-src/ffmpeg release/
        cp ffmpeg-src/ffprobe release/
        cd release
        tar -czf ../ffmpeg-apple-silicon-native-${{ github.ref_name }}.tar.gz *
        cd ..
        shasum -a 256 ffmpeg-apple-silicon-native-${{ github.ref_name }}.tar.gz > checksums.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-apple-silicon-native
        path: |
          ffmpeg-apple-silicon-native-*.tar.gz
          checksums.txt
